version: '3'

services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/html
